import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  inlineNameOverlay: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  inlineNamePanel: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.42)",
    borderColor: "rgba(255,240,122,0.74)",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    gap: 8,
    minHeight: 58,
    paddingHorizontal: 8,
    paddingVertical: 7,
  },
  inlineNameInput: {
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: 6,
    borderWidth: 1,
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    height: 44,
    lineHeight: 20,
    paddingHorizontal: 10,
    paddingVertical: 0,
    textAlign: "center",
    textAlignVertical: "center",
    width: 190,
  },
  inlineNameConfirm: {
    alignItems: "center",
    backgroundColor: "#fff07a",
    borderRadius: 6,
    height: 44,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  inlineNameConfirmText: {
    color: "#17201d",
    fontSize: 13,
    fontWeight: "900",
  },
  background: {
    backgroundColor: "#095c39",
    flex: 1,
  },
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  screen: {
    alignItems: "center",
    flex: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  header: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 104,
    position: "relative",
  },
  headerLeftSlot: {
    alignItems: "flex-start",
    gap: 8,
    width: 44,
  },
  achievementHeaderButton: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
    borderColor: "rgba(255,240,122,0.72)",
    borderRadius: 8,
    borderWidth: 2,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  achievementHeaderIcon: {
    color: "#fff07a",
    fontSize: 21,
    fontWeight: "900",
    lineHeight: 24,
  },
  profileHeaderButton: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
    borderColor: "rgba(255,255,255,0.46)",
    borderRadius: 8,
    borderWidth: 2,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  profileHeaderIcon: {
    alignItems: "center",
    height: 22,
    justifyContent: "center",
    width: 22,
  },
  profileHeaderIconHead: {
    backgroundColor: "#ffffff",
    borderRadius: 5,
    height: 8,
    marginBottom: 2,
    width: 8,
  },
  profileHeaderIconBody: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 9,
    borderTopRightRadius: 9,
    height: 8,
    width: 17,
  },
  soundHeaderButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    height: 50,
    justifyContent: "center",
    left: "50%",
    marginLeft: -25,
    position: "absolute",
    top: 0,
    width: 50,
  },
  soundHeaderIcon: {
    borderRadius: 4,
    height: 32,
    width: 32,
  },
  headerRight: {
    alignItems: "flex-end",
    gap: 2,
  },
  accountMenuButton: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.24)",
    borderRadius: 7,
    flexDirection: "row",
    gap: 6,
    maxWidth: 126,
    minHeight: 34,
    paddingHorizontal: 9,
  },
  menuIcon: {
    gap: 3,
    width: 15,
  },
  menuIconLine: {
    backgroundColor: "#ffffff",
    borderRadius: 2,
    height: 2,
    width: 15,
  },
  accountMenuButtonText: {
    color: "#ffffff",
    flexShrink: 1,
    fontSize: 11,
    fontWeight: "900",
  },
  accountModalBackdrop: {
    backgroundColor: "rgba(0,0,0,0.58)",
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 58,
  },
  accountPanel: {
    alignSelf: "flex-end",
    backgroundColor: "#f7f9f4",
    borderColor: "#111111",
    borderRadius: 8,
    borderWidth: 2,
    maxHeight: "78%",
    padding: 14,
    width: 310,
  },
  accountPanelHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  accountPanelTitle: {
    color: "#17201d",
    fontSize: 22,
    fontWeight: "900",
  },
  accountCloseButton: {
    alignItems: "center",
    backgroundColor: "#d63d3d",
    borderRadius: 8,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  accountCloseText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
  },
  accountListScroll: {
    maxHeight: 360,
  },
  accountList: {
    gap: 8,
  },
  accountRow: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#cbd5cf",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 64,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  accountSelectArea: {
    flex: 1,
    justifyContent: "center",
    minHeight: 44,
  },
  accountRowActions: {
    alignItems: "flex-end",
    gap: 6,
  },
  accountEditButton: {
    alignItems: "center",
    backgroundColor: "#17201d",
    borderRadius: 6,
    justifyContent: "center",
    minHeight: 28,
    minWidth: 48,
    paddingHorizontal: 8,
  },
  accountEditButtonText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  accountRenameInput: {
    backgroundColor: "#ffffff",
    borderColor: "#0f9f5a",
    borderRadius: 6,
    borderWidth: 2,
    color: "#17201d",
    flex: 1,
    fontSize: 15,
    fontWeight: "900",
    minHeight: 42,
    paddingHorizontal: 9,
  },
  accountRenameActions: {
    flexDirection: "row",
    gap: 6,
    marginLeft: 8,
  },
  accountRenameSave: {
    alignItems: "center",
    backgroundColor: "#0f9f5a",
    borderRadius: 6,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 9,
  },
  accountRenameSaveText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "900",
  },
  accountRenameCancel: {
    alignItems: "center",
    backgroundColor: "#d63d3d",
    borderRadius: 6,
    justifyContent: "center",
    minHeight: 36,
    width: 32,
  },
  accountRenameCancelText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "900",
  },
  accountRowActive: {
    backgroundColor: "#e6fff0",
    borderColor: "#0f9f5a",
  },
  accountRowDisabled: {
    opacity: 0.52,
  },
  accountName: {
    color: "#17201d",
    fontSize: 16,
    fontWeight: "900",
  },
  accountCredit: {
    color: "#68746f",
    fontSize: 14,
    fontWeight: "800",
    marginTop: 2,
  },
  activeAccountText: {
    color: "#0b7c45",
    fontSize: 11,
    fontWeight: "900",
  },
  accountMenuMessage: {
    color: "#b32626",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 10,
    textAlign: "center",
  },
  createAccountButton: {
    alignItems: "center",
    backgroundColor: "#fff07a",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  createAccountButtonText: {
    color: "#17201d",
    fontSize: 16,
    fontWeight: "900",
  },
  createAccountCost: {
    color: "#17201d",
    fontSize: 15,
    fontWeight: "900",
  },
  achievementModalBackdrop: {
    backgroundColor: "rgba(0,0,0,0.72)",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 42,
  },
  achievementModalCloseLayer: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  achievementPanel: {
    alignSelf: "center",
    backgroundColor: "rgba(8,26,18,0.98)",
    borderColor: "rgba(255,240,122,0.78)",
    borderRadius: 8,
    borderWidth: 2,
    height: "88%",
    maxHeight: "92%",
    maxWidth: 420,
    padding: 14,
    width: "100%",
  },
  achievementPanelHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  achievementPanelTitle: {
    color: "#fff07a",
    fontSize: 28,
    fontWeight: "900",
  },
  achievementPanelEyebrow: {
    color: "rgba(214,255,231,0.68)",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  achievementPanelSubtitle: {
    color: "#d6ffe7",
    fontSize: 12,
    fontWeight: "900",
    marginTop: 2,
  },
  achievementHeaderCopy: {
    flex: 1,
  },
  achievementCloseButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderColor: "rgba(255,255,255,0.3)",
    borderRadius: 8,
    borderWidth: 2,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  achievementCloseText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  achievementSummaryCard: {
    backgroundColor: "rgba(255,240,122,0.12)",
    borderColor: "rgba(255,240,122,0.42)",
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 12,
    padding: 12,
  },
  achievementSummaryTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  achievementSummaryLabel: {
    color: "rgba(255,255,255,0.66)",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  achievementSummaryValue: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "900",
    marginTop: 1,
  },
  achievementSummaryBadge: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
    borderColor: "rgba(214,255,231,0.32)",
    borderRadius: 7,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 30,
    paddingHorizontal: 10,
  },
  achievementSummaryBadgeText: {
    color: "#d6ffe7",
    fontSize: 11,
    fontWeight: "900",
  },
  achievementSummaryTrack: {
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 6,
    height: 9,
    marginTop: 10,
    overflow: "hidden",
  },
  achievementSummaryFill: {
    backgroundColor: "#fff07a",
    borderRadius: 6,
    height: "100%",
  },
  achievementListScroll: {
    flex: 1,
    minHeight: 220,
  },
  achievementList: {
    gap: 10,
    paddingBottom: 6,
  },
  achievementRow: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderColor: "rgba(255,255,255,0.16)",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 112,
    padding: 11,
  },
  achievementRowUnlocked: {
    backgroundColor: "rgba(24,201,111,0.14)",
    borderColor: "rgba(44,226,135,0.7)",
  },
  achievementBadge: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderColor: "rgba(214,224,224,0.42)",
    borderRadius: 21,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    marginRight: 11,
    width: 42,
  },
  achievementBadgeUnlocked: {
    backgroundColor: "rgba(255,240,122,0.18)",
    borderColor: "#fff7ad",
  },
  achievementBadgeText: {
    color: "#c8d0d0",
    fontSize: 21,
    fontWeight: "900",
  },
  achievementBadgeTextUnlocked: {
    color: "#fff07a",
  },
  achievementInfo: {
    flex: 1,
  },
  achievementTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  achievementTitle: {
    color: "#ffffff",
    flex: 1,
    fontSize: 15,
    fontWeight: "900",
  },
  achievementStatus: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 5,
    color: "rgba(255,255,255,0.62)",
    fontSize: 9,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  achievementStatusUnlocked: {
    backgroundColor: "#fff07a",
    color: "#17201d",
  },
  achievementDescription: {
    color: "#ffffff",
    flex: 1,
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
  },
  achievementTaskRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 6,
    marginTop: 6,
  },
  achievementTaskLabel: {
    backgroundColor: "rgba(255,240,122,0.18)",
    borderColor: "rgba(255,240,122,0.46)",
    borderRadius: 5,
    borderWidth: 1,
    color: "#fff07a",
    fontSize: 8,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  achievementProgressTrack: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 5,
    height: 7,
    marginTop: 9,
    overflow: "hidden",
  },
  achievementProgressFill: {
    backgroundColor: "#2ce287",
    borderRadius: 5,
    height: "100%",
  },
  achievementFooterRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 6,
  },
  achievementProgressText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 10,
    fontWeight: "900",
  },
  achievementRewardText: {
    color: "#fff07a",
    fontSize: 10,
    fontWeight: "900",
  },
  achievementToast: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(12,24,19,0.94)",
    borderColor: "#fff07a",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    gap: 10,
    left: 18,
    minHeight: 86,
    paddingHorizontal: 12,
    paddingVertical: 9,
    position: "absolute",
    right: 18,
    top: 64,
    zIndex: 80,
  },
  achievementToastCheck: {
    alignItems: "center",
    backgroundColor: "#18c96f",
    borderColor: "#d6ffe7",
    borderRadius: 18,
    borderWidth: 2,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  achievementToastCheckText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 24,
  },
  achievementToastTextWrap: {
    flex: 1,
  },
  achievementToastEyebrow: {
    color: "#fff07a",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  achievementToastTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    marginTop: 1,
  },
  achievementToastDescription: {
    color: "#d6ffe7",
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  achievementToastReward: {
    color: "#fff07a",
    fontSize: 11,
    fontWeight: "900",
    marginTop: 3,
  },
  profileScreen: {
    backgroundColor: "rgba(6,38,25,0.94)",
    bottom: 0,
    left: 0,
    paddingHorizontal: 12,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 90,
  },
  profileTopBar: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 54,
  },
  profileTopBarTablet: {
    minHeight: 72,
  },
  profileBackButton: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
    borderColor: "rgba(255,255,255,0.28)",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    minWidth: 68,
    paddingHorizontal: 12,
  },
  profileBackButtonTablet: {
    minHeight: 50,
    minWidth: 92,
    paddingHorizontal: 18,
  },
  profileBackText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  profileBackTextTablet: {
    fontSize: 17,
  },
  profileTitleWrap: {
    alignItems: "center",
    flex: 1,
  },
  profileTitle: {
    color: "#fff07a",
    fontSize: 24,
    fontWeight: "900",
  },
  profileTitleTablet: {
    fontSize: 34,
  },
  profileAccountName: {
    color: "#d6ffe7",
    fontSize: 12,
    fontWeight: "800",
    marginTop: 1,
    maxWidth: 170,
  },
  profileAccountNameTablet: {
    fontSize: 16,
    maxWidth: 260,
  },
  profileTopSpacer: {
    width: 68,
  },
  profileTopSpacerTablet: {
    width: 92,
  },
  profileStatsContent: {
    paddingBottom: 24,
    paddingTop: 10,
  },
  profileStatsContentTablet: {
    paddingBottom: 34,
    paddingTop: 16,
  },
  profileHero: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
    borderColor: "rgba(255,240,122,0.45)",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    marginBottom: 12,
    minHeight: 96,
    paddingHorizontal: 16,
  },
  profileHeroTablet: {
    marginBottom: 16,
    minHeight: 132,
    paddingHorizontal: 24,
  },
  profileAvatar: {
    alignItems: "center",
    backgroundColor: "rgba(255,240,122,0.16)",
    borderColor: "#fff07a",
    borderRadius: 28,
    borderWidth: 2,
    height: 56,
    justifyContent: "center",
    marginRight: 14,
    width: 56,
  },
  profileAvatarTablet: {
    borderRadius: 38,
    height: 76,
    marginRight: 20,
    width: 76,
  },
  profileAvatarHead: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    height: 14,
    marginBottom: 3,
    width: 14,
  },
  profileAvatarHeadTablet: {
    borderRadius: 10,
    height: 20,
    marginBottom: 5,
    width: 20,
  },
  profileAvatarBody: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
    height: 14,
    width: 30,
  },
  profileAvatarBodyTablet: {
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    height: 18,
    width: 42,
  },
  profileHeroText: {
    flex: 1,
  },
  profileHeroLabel: {
    color: "#d6ffe7",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  profileHeroLabelTablet: {
    fontSize: 16,
  },
  profileHeroValue: {
    color: "#fff07a",
    fontSize: 30,
    fontWeight: "900",
    marginTop: 2,
  },
  profileHeroValueTablet: {
    fontSize: 42,
    marginTop: 4,
  },
  profileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  profileGridTablet: {
    gap: 12,
  },
  profileStatCard: {
    backgroundColor: "rgba(0,0,0,0.26)",
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 70,
    paddingHorizontal: 10,
    paddingVertical: 9,
    width: "48%",
  },
  profileStatCardTablet: {
    minHeight: 96,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  profileStatLabel: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  profileStatLabelTablet: {
    fontSize: 13,
  },
  profileStatValue: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
    marginTop: 7,
  },
  profileStatValueTablet: {
    fontSize: 24,
    marginTop: 10,
  },
  wallet: {
    alignItems: "flex-end",
    paddingVertical: 6,
    position: "relative",
  },
  walletLabelRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
  },
  walletLabel: {
    color: "#d6ffe7",
    fontSize: 12,
    fontWeight: "800",
  },
  walletValue: {
    color: "#fff07a",
    fontSize: 24,
    fontWeight: "900",
  },
  rewardedAdButton: {
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: "rgba(255,240,122,0.16)",
    borderColor: "rgba(255,240,122,0.7)",
    borderRadius: 7,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    marginTop: 3,
    minHeight: 22,
    paddingHorizontal: 7,
  },
  rewardedAdBadge: {
    backgroundColor: "#fff07a",
    borderRadius: 4,
    color: "#17201d",
    fontSize: 8,
    fontWeight: "900",
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  rewardedAdText: {
    color: "#fff07a",
    fontSize: 10,
    fontWeight: "900",
  },
  rewardedAdStatus: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 9,
    fontWeight: "900",
    marginTop: 2,
    maxWidth: 94,
    textAlign: "right",
  },
  startupSplash: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#031f09",
    zIndex: 999,
  },
  creditDelta: {
    fontSize: 14,
    fontWeight: "900",
    position: "absolute",
    right: 0,
    top: 62,
  },
  creditDeltaPositive: {
    color: "#fff07a",
  },
  creditDeltaNegative: {
    color: "#ffdddd",
  },
  blackjackCelebration: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.72)",
    borderColor: "#fff07a",
    borderRadius: 8,
    borderWidth: 2,
    left: 18,
    paddingHorizontal: 18,
    paddingVertical: 16,
    position: "absolute",
    right: 18,
    top: "40%",
    zIndex: 20,
  },
  blackjackCelebrationLine: {
    backgroundColor: "#fff07a",
    height: 2,
    width: "84%",
  },
  blackjackCelebrationText: {
    color: "#fff07a",
    fontSize: 34,
    fontWeight: "900",
    marginVertical: 7,
    textShadowColor: "rgba(255,240,122,0.45)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 9,
  },
  blackjackCelebrationSuits: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 7,
  },
  table: {
    alignSelf: "center",
    flex: 1,
    justifyContent: "space-between",
    paddingBottom: 10,
  },
  hand: {
    alignItems: "center",
    minHeight: 198,
  },
  handTablet: {
    minHeight: 222,
  },
  handHeader: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    minHeight: 34,
  },
  score: {
    minWidth: 42,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.2)",
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    textAlign: "center",
  },
  scoreTablet: {
    fontSize: 18,
    minWidth: 48,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  dealerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
    minHeight: 112,
  },
  dealerRowTablet: {
    gap: 14,
    minHeight: 136,
  },
  deckShoe: {
    height: 113,
    position: "relative",
    width: 72,
  },
  deckShoeTablet: {
    height: 135,
    width: 86,
  },
  deckShoePressed: {
    opacity: 0.92,
  },
  deckCard: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderColor: "#111111",
    borderRadius: 8,
    borderWidth: 2,
    height: 113,
    justifyContent: "center",
    position: "absolute",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 10,
    width: 72,
    elevation: 6,
  },
  deckCardTablet: {
    height: 135,
    width: 86,
  },
  deckCardImage: {
    borderRadius: 8,
    height: "100%",
    width: "100%",
  },
  deckCardPattern: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderColor: "rgba(0,0,0,0.24)",
    borderRadius: 6,
    borderWidth: 2,
    height: 58,
    width: 36,
  },
  cards: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center",
    maxWidth: 300,
  },
  stackedCards: {
    height: 147,
    position: "relative",
  },
  stackedCardsTablet: {
    height: 172,
  },
  stackedCardSlot: {
    position: "absolute",
    top: 0,
  },
  card: {
    width: 94,
    height: 147,
    overflow: "hidden",
    borderColor: "#111111",
    borderWidth: 2,
    borderRadius: 8,
    backgroundColor: "transparent",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 10,
    elevation: 6,
  },
  cardTablet: {
    height: 172,
    width: 108,
  },
  compactCard: {
    width: 82,
    height: 128,
  },
  compactCardTablet: {
    height: 147,
    width: 94,
  },
  cardBack: {
    borderColor: "#fff8ec",
    borderWidth: 4,
    backgroundColor: "#8d1f2d",
    justifyContent: "center",
    alignItems: "center",
  },
  cardBackPattern: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
    borderColor: "rgba(0,0,0,0.24)",
    borderRadius: 6,
    borderWidth: 2,
    height: "72%",
    justifyContent: "center",
    width: "64%",
  },
  cardBackPatternInner: {
    borderColor: "rgba(255,255,255,0.42)",
    borderRadius: 4,
    borderWidth: 2,
    height: 42,
    width: 24,
  },
  cardFaceLine: {
    borderColor: "rgba(0,0,0,0.12)",
    borderRadius: 5,
    borderWidth: 1,
    bottom: 5,
    left: 5,
    position: "absolute",
    right: 5,
    top: 5,
  },
  cardTopCorner: {
    alignItems: "center",
    left: 8,
    position: "absolute",
    top: 8,
    width: 22,
  },
  cardRank: {
    color: "#17201d",
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 20,
  },
  cardCornerSuit: {
    color: "#17201d",
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 14,
  },
  compactCardRank: {
    fontSize: 18,
    lineHeight: 18,
  },
  compactCornerSuit: {
    fontSize: 12,
    lineHeight: 12,
  },
  cardSuit: {
    color: "#17201d",
    fontSize: 38,
    fontWeight: "900",
    left: 0,
    lineHeight: 42,
    position: "absolute",
    right: 0,
    textAlign: "center",
    top: 36,
  },
  compactCardSuit: {
    fontSize: 32,
    lineHeight: 36,
    top: 34,
  },
  cardBottomCorner: {
    alignItems: "center",
    bottom: 8,
    position: "absolute",
    right: 8,
    transform: [{ rotate: "180deg" }],
    width: 22,
  },
  redCard: {
    color: "#d54848",
  },
  blackjackHandClip: {
    alignSelf: "center",
    minHeight: 198,
    overflow: "hidden",
  },
  blackjackHandClipTablet: {
    minHeight: 224,
  },
  centerControls: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 190,
  },
  tabArea: {
    height: 286,
    position: "relative",
  },
  tabAreaTablet: {
    height: 326,
  },
  tabViewport: {
    alignSelf: "center",
    height: 286,
    overflow: "hidden",
  },
  tabViewportTablet: {
    height: 326,
  },
  tabTrack: {
    flexDirection: "row",
    height: "100%",
  },
  tabPanel: {
    alignItems: "center",
    height: "100%",
    justifyContent: "center",
  },
  blackjackOverlayClip: {
    height: 378,
    left: 0,
    overflow: "hidden",
    position: "absolute",
    top: -92,
  },
  blackjackOverlayClipTablet: {
    height: 426,
    top: -100,
  },
  blackjackBetOverlay: {
    alignItems: "center",
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
    top: 34,
  },
  blackjackBetOverlayTablet: {
    top: 24,
  },
  storeOverlayClip: {
    height: 532,
    left: 0,
    overflow: "hidden",
    position: "absolute",
    top: -246,
  },
  storeOverlayClipTablet: {
    height: 610,
    top: -278,
  },
  storeOverlay: {
    height: 509,
    left: 0,
    position: "absolute",
    right: 0,
    top: 3,
  },
  storeOverlayTablet: {
    height: 584,
  },
  moneyOverlayClip: {
    height: 507,
    left: 0,
    overflow: "hidden",
    position: "absolute",
    top: -221,
  },
  moneyOverlayClipTablet: {
    height: 612,
    top: -282,
  },
  moneyOverlay: {
    height: 484,
    left: 0,
    position: "absolute",
    right: 0,
    top: 23,
  },
  moneyOverlayTablet: {
    height: 548,
    top: 23,
  },
  storeScreen: {
    alignItems: "center",
    height: "100%",
    paddingBottom: 7,
    paddingTop: 8,
  },
  storeTitle: {
    color: "#fff07a",
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 8,
    textAlign: "center",
  },
  storeTitleTablet: {
    fontSize: 28,
    marginBottom: 10,
  },
  storeCategories: {
    backgroundColor: "rgba(0,0,0,0.24)",
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    marginBottom: 8,
    padding: 4,
    width: "92%",
  },
  storeCategoriesTablet: {
    marginBottom: 10,
    padding: 5,
  },
  storeCategoryButton: {
    alignItems: "center",
    borderRadius: 6,
    flex: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: 8,
  },
  storeCategoryButtonTablet: {
    minHeight: 44,
  },
  storeCategoryButtonSelected: {
    backgroundColor: "#fff07a",
  },
  storeCategoryText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  storeCategoryTextTablet: {
    fontSize: 14,
  },
  storeCategoryTextSelected: {
    color: "#17201d",
  },
  storeList: {
    backgroundColor: "rgba(0,0,0,0.22)",
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    width: "92%",
  },
  storeListContent: {
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  storeListing: {
    alignItems: "center",
    borderBottomColor: "rgba(255,255,255,0.14)",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 64,
    paddingHorizontal: 4,
  },
  storeListingTablet: {
    minHeight: 78,
    paddingHorizontal: 6,
  },
  storeListingInfo: {
    alignItems: "center",
    flexDirection: "row",
    flex: 1,
    flexShrink: 1,
  },
  storeListingLabel: {
    flexShrink: 1,
    marginLeft: 9,
  },
  storeListingTier: {
    color: "rgba(255,255,255,0.48)",
    fontSize: 9,
    fontWeight: "900",
  },
  storeListingTierTablet: {
    fontSize: 10,
  },
  storeListingName: {
    color: "#ffffff",
    flexShrink: 1,
    fontSize: 14,
    fontWeight: "900",
  },
  storeListingNameTablet: {
    fontSize: 16,
  },
  storeListingBonus: {
    color: "rgba(255,255,255,0.58)",
    flexShrink: 1,
    fontSize: 9,
    fontWeight: "900",
    marginTop: 1,
  },
  storeListingBonusTablet: {
    fontSize: 10,
    marginTop: 2,
  },
  storeListingPrice: {
    color: "#fff07a",
    fontSize: 12,
    fontWeight: "900",
  },
  storeListingPriceTablet: {
    fontSize: 14,
  },
  storeBuyButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,240,122,0.1)",
    borderColor: "#fff07a",
    borderRadius: 6,
    borderWidth: 2,
    justifyContent: "center",
    marginLeft: 8,
    minHeight: 34,
    minWidth: 88,
    paddingHorizontal: 7,
  },
  storeBuyButtonTablet: {
    minHeight: 40,
    minWidth: 104,
    paddingHorizontal: 9,
  },
  storeBuyButtonOwned: {
    backgroundColor: "rgba(44,226,135,0.2)",
    borderColor: "#2ce287",
  },
  storeBuyButtonDisabled: {
    opacity: 0.42,
  },
  storeOwnedCheck: {
    color: "#2ce287",
    fontSize: 19,
    fontWeight: "900",
  },
  storeRentRate: {
    color: "#2ce287",
    fontSize: 10,
    fontWeight: "900",
  },
  storeOwnedLabel: {
    alignItems: "center",
    height: 24,
    justifyContent: "center",
    width: 74,
  },
  storeOwnedLabelText: {
    position: "absolute",
    textAlign: "center",
    width: "100%",
  },
  propertyThumbnail: {
    alignItems: "center",
    backgroundColor: "#17201d",
    borderColor: "rgba(255,255,255,0.76)",
    borderRadius: 5,
    borderWidth: 2,
    height: 44,
    justifyContent: "center",
    overflow: "hidden",
    width: 44,
  },
  storeThumbnailTablet: {
    height: 54,
    width: 54,
  },
  vehicleThumbnail: {
    alignItems: "center",
    backgroundColor: "#17201d",
    borderColor: "rgba(255,255,255,0.76)",
    borderRadius: 5,
    borderWidth: 2,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  itemThumbnail: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    borderColor: "rgba(255,255,255,0.76)",
    borderRadius: 5,
    borderWidth: 2,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  storeThumbnailImage: {
    height: "100%",
    width: "100%",
  },
  storeEmptyCategory: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.22)",
    borderColor: "rgba(255,255,255,0.18)",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    width: "92%",
  },
  storeEmptyTitle: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "900",
  },
  storeEmptyText: {
    color: "#d6ffe7",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 6,
  },
  rentalPanel: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.34)",
    borderColor: "rgba(255,255,255,0.24)",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    marginTop: 7,
    minHeight: 68,
    paddingHorizontal: 9,
    paddingVertical: 6,
    width: "92%",
  },
  rentalPanelInfo: {
    flex: 1,
  },
  rentalPanelTitle: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  rentalPanelRate: {
    color: "#2ce287",
    fontSize: 10,
    fontWeight: "900",
    marginTop: 2,
  },
  rentalPanelCapacity: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 8,
    fontWeight: "900",
    marginTop: 1,
  },
  rentalProgressTrack: {
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 5,
    height: 6,
    marginTop: 4,
    overflow: "hidden",
    width: 98,
  },
  rentalProgressFill: {
    backgroundColor: "#2ce287",
    borderRadius: 5,
    height: "100%",
  },
  rentalCountdown: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 8,
    fontWeight: "900",
    marginTop: 2,
  },
  rentalPanelAmount: {
    color: "#fff07a",
    fontSize: 15,
    fontWeight: "900",
    marginHorizontal: 8,
  },
  rentalCollectButton: {
    alignItems: "center",
    backgroundColor: "#18c96f",
    borderRadius: 7,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: 12,
  },
  rentalCollectText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "900",
  },
  moneyMachineScreen: {
    alignItems: "center",
    height: "100%",
    justifyContent: "space-between",
    paddingBottom: 6,
    paddingTop: 8,
  },
  moneyMachineStation: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.25)",
    borderColor: "rgba(255,255,255,0.22)",
    borderRadius: 8,
    borderWidth: 2,
    gap: 5,
    justifyContent: "center",
    minHeight: 174,
    paddingHorizontal: 14,
    paddingVertical: 7,
    width: "88%",
  },
  moneyMachineStationTablet: {
    minHeight: 196,
    paddingHorizontal: 18,
    width: "90%",
  },
  moneyMachineStationTitle: {
    color: "#fff07a",
    fontSize: 19,
    fontWeight: "900",
    textAlign: "center",
  },
  moneyMachineStationTitleTablet: {
    fontSize: 22,
  },
  moneyMachineBox: {
    alignItems: "center",
    backgroundColor: "#17201d",
    borderColor: "#fff07a",
    borderRadius: 8,
    borderWidth: 2,
    gap: 5,
    minHeight: 84,
    paddingHorizontal: 16,
    paddingVertical: 6,
    width: 220,
  },
  moneyMachineBoxTablet: {
    minHeight: 98,
    paddingHorizontal: 16,
    paddingVertical: 6,
    width: 260,
  },
  moneyMachineTapZone: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.13)",
    borderColor: "rgba(255,255,255,0.3)",
    borderRadius: 8,
    borderWidth: 2,
    height: 220,
    justifyContent: "center",
    transform: [{ translateY: -23 }],
    width: "92%",
  },
  moneyMachineTapZoneTablet: {
    height: 244,
    width: "94%",
  },
  moneyMachineTapZoneFull: {
    opacity: 0.55,
  },
  moneyMachineTapZonePressed: {
    backgroundColor: "rgba(255,240,122,0.28)",
    transform: [{ translateY: -23 }, { scale: 0.985 }],
  },
  moneyMachineTapZonePressedTablet: {
    transform: [{ translateY: -23 }, { scale: 0.99 }],
  },
  moneyMachineTapText: {
    color: "#ffffff",
    fontSize: 23,
    fontWeight: "900",
    maxWidth: 260,
    textAlign: "center",
  },
  moneyMachineTapTextTablet: {
    fontSize: 26,
    maxWidth: 340,
  },
  moneyMachineTapValue: {
    color: "#fff07a",
    fontSize: 18,
    fontWeight: "900",
    marginTop: 10,
  },
  moneyMachineTapValueTablet: {
    fontSize: 21,
  },
  moneyMachineUpgrades: {
    flexDirection: "row",
    gap: 8,
    height: 68,
    justifyContent: "center",
    transform: [{ translateY: -12 }],
    width: "92%",
  },
  moneyMachineUpgradesTablet: {
    height: 78,
    width: "94%",
  },
  moneyMachineUpgrade: {
    alignItems: "center",
    backgroundColor: "rgba(255,240,122,0.18)",
    borderColor: "#fff07a",
    borderRadius: 7,
    borderWidth: 2,
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  moneyMachineUpgradeTablet: {
    paddingHorizontal: 8,
  },
  moneyMachineUpgradeDisabled: {
    opacity: 0.48,
  },
  moneyMachineUpgradeTitle: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "center",
  },
  moneyMachineUpgradeTitleTablet: {
    fontSize: 15,
  },
  moneyMachineUpgradeEffect: {
    color: "#d6ffe7",
    fontSize: 10,
    fontWeight: "800",
    marginTop: 2,
    textAlign: "center",
  },
  moneyMachineUpgradeEffectTablet: {
    fontSize: 11,
  },
  moneyMachineUpgradeCost: {
    color: "#fff07a",
    fontSize: 10,
    fontWeight: "900",
    marginTop: 2,
    textAlign: "center",
  },
  moneyMachineUpgradeCostTablet: {
    fontSize: 11,
  },
  moneyMachineTopLight: {
    backgroundColor: "#18c96f",
    borderRadius: 6,
    height: 9,
    width: 38,
  },
  moneyMachineTopLightTablet: {
    height: 10,
    width: 46,
  },
  moneyMachineWindow: {
    alignItems: "center",
    backgroundColor: "#06110b",
    borderColor: "#2ce287",
    borderRadius: 7,
    borderWidth: 2,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 5,
    width: "100%",
  },
  moneyMachineWindowTablet: {
    minHeight: 58,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  moneyMachineAmount: {
    color: "#2ce287",
    fontSize: 22,
    fontWeight: "900",
  },
  moneyMachineAmountTablet: {
    fontSize: 25,
  },
  moneyMachineAmountRow: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  moneyMachinePassiveRate: {
    color: "#fff07a",
    fontSize: 9,
    fontWeight: "900",
    marginTop: 2,
  },
  moneyMachinePassiveRateTablet: {
    fontSize: 10,
    marginTop: 3,
  },
  moneyMachineProgressTrack: {
    backgroundColor: "rgba(255,255,255,0.16)",
    borderRadius: 6,
    height: 10,
    overflow: "hidden",
    width: "100%",
  },
  moneyMachineProgressTrackTablet: {
    height: 11,
  },
  moneyMachineProgressFill: {
    backgroundColor: "#fff07a",
    borderRadius: 6,
    height: "100%",
  },
  moneyMachineCapacity: {
    color: "#d6ffe7",
    fontSize: 10,
    fontWeight: "900",
  },
  moneyMachineCapacityTablet: {
    fontSize: 11,
  },
  moneyMachineCollect: {
    alignItems: "center",
    backgroundColor: "#18c96f",
    borderRadius: 8,
    justifyContent: "center",
    minHeight: 25,
    paddingHorizontal: 28,
  },
  moneyMachineCollectTablet: {
    minHeight: 30,
    paddingHorizontal: 34,
  },
  moneyMachineCollectText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "900",
  },
  moneyMachineCollectTextTablet: {
    fontSize: 15,
  },
  bottomTabs: {
    alignSelf: "center",
    backgroundColor: "rgba(0,0,0,0.28)",
    borderColor: "rgba(255,255,255,0.14)",
    borderRadius: 8,
    borderWidth: 2,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: 291,
  },
  bottomTabsTablet: {
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: 339,
  },
  bottomTabButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: 7,
    height: 85,
    justifyContent: "center",
    width: 85,
  },
  bottomTabButtonTablet: {
    height: 99,
    width: 99,
  },
  bottomTabButtonSelected: {
    backgroundColor: "rgba(255,240,122,0.86)",
  },
  bottomTabIcon: {
    height: 48,
    opacity: 0.9,
    tintColor: "#ffffff",
    width: 48,
  },
  bottomTabIconTablet: {
    height: 56,
    width: 56,
  },
  bottomTabIconSelected: {
    opacity: 1,
    tintColor: "#17201d",
  },
  message: {
    minHeight: 24,
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 4,
    textAlign: "center",
  },
  betStack: {
    alignItems: "center",
    height: 74,
    justifyContent: "flex-end",
    marginBottom: 10,
    width: 84,
  },
  betStackTablet: {
    height: 98,
    width: 108,
  },
  stackedChip: {
    position: "absolute",
  },
  emptyBetSpace: {
    height: 54,
    width: 54,
  },
  emptyBetSpaceTablet: {
    height: 80,
    width: 80,
  },
  betRow: {
    flexDirection: "row",
    gap: 4,
    justifyContent: "center",
    marginBottom: 2,
    minHeight: 78,
  },
  betRowTablet: {
    gap: 8,
    minHeight: 108,
  },
  chipButton: {
    borderRadius: 31,
  },
  chipButtonTablet: {
    borderRadius: 44,
  },
  chipButton0: {
    transform: [{ translateY: 18 }, { rotate: "-12deg" }],
  },
  chipButton0Tablet: {
    transform: [{ translateY: 22 }, { rotate: "-12deg" }],
  },
  chipButton1: {
    transform: [{ translateY: 1 }, { rotate: "-6deg" }],
  },
  chipButton1Tablet: {
    transform: [{ translateY: 1 }, { rotate: "-6deg" }],
  },
  chipButton2: {
    transform: [{ translateY: -7 }],
  },
  chipButton2Tablet: {
    transform: [{ translateY: -9 }],
  },
  chipButton3: {
    transform: [{ translateY: 1 }, { rotate: "6deg" }],
  },
  chipButton3Tablet: {
    transform: [{ translateY: 1 }, { rotate: "6deg" }],
  },
  chipButton4: {
    transform: [{ translateY: 18 }, { rotate: "12deg" }],
  },
  chipButton4Tablet: {
    transform: [{ translateY: 22 }, { rotate: "12deg" }],
  },
  chipOuter: {
    alignItems: "center",
    borderColor: "#111111",
    borderRadius: 31,
    borderWidth: 3,
    height: 62,
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.28,
    shadowRadius: 7,
    width: 62,
    elevation: 7,
  },
  chipOuterTablet: {
    borderRadius: 44,
    height: 82,
    width: 82,
  },
  chipOuterSmall: {
    borderRadius: 27,
    height: 54,
    width: 54,
  },
  chipOuterSmallTablet: {
    borderRadius: 38,
    height: 76,
    width: 76,
  },
  chipInner: {
    alignItems: "center",
    backgroundColor: "#f7f9f4",
    borderColor: "#0f2019",
    borderRadius: 22,
    borderWidth: 2,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  chipInnerTablet: {
    borderRadius: 30,
    height: 58,
    width: 58,
  },
  chipInnerSmall: {
    borderRadius: 18,
    height: 36,
    width: 36,
  },
  chipInnerSmallTablet: {
    borderRadius: 25,
    height: 50,
    width: 50,
  },
  chipStripeTop: {
    backgroundColor: "#ffffff",
    height: 14,
    position: "absolute",
    top: -1,
    width: 11,
  },
  chipStripeTopTablet: {
    height: 16,
    width: 13,
  },
  chipStripeRight: {
    backgroundColor: "#ffffff",
    height: 11,
    position: "absolute",
    right: -1,
    width: 14,
  },
  chipStripeRightTablet: {
    height: 13,
    width: 16,
  },
  chipStripeBottom: {
    backgroundColor: "#ffffff",
    bottom: -1,
    height: 14,
    position: "absolute",
    width: 11,
  },
  chipStripeBottomTablet: {
    height: 16,
    width: 13,
  },
  chipStripeLeft: {
    backgroundColor: "#ffffff",
    height: 11,
    left: -1,
    position: "absolute",
    width: 14,
  },
  chipStripeLeftTablet: {
    height: 13,
    width: 16,
  },
  chipText: {
    color: "#111111",
    fontSize: 14,
    fontWeight: "900",
  },
  chipTextTablet: {
    fontSize: 18,
  },
  chipTextSmall: {
    fontSize: 11,
  },
  chipTextSmallTablet: {
    fontSize: 15,
  },
  chipText5000: {
    fontSize: 12,
  },
  chipText5000Tablet: {
    fontSize: 15,
  },
  chipText5000Small: {
    fontSize: 9,
  },
  chipText5000SmallTablet: {
    fontSize: 12,
  },
  betActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
  },
  betActionsTablet: {
    gap: 10,
  },
  dealButton: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 104,
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: "#fff07a",
  },
  dealButtonText: {
    color: "#17201d",
    fontSize: 17,
    fontWeight: "900",
  },
  clearButton: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 104,
    minHeight: 50,
    borderRadius: 8,
    backgroundColor: "rgba(0,0,0,0.24)",
  },
  clearButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  totalBetBadge: {
    alignItems: "center",
    backgroundColor: "#21d9d0",
    borderRadius: 34,
    height: 68,
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.18,
    shadowRadius: 7,
    width: 68,
    elevation: 6,
  },
  totalBetText: {
    color: "#063226",
    fontSize: 18,
    fontWeight: "900",
  },
  totalBetTextCompact: {
    fontSize: 14,
  },
  roundLoader: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 118,
  },
  roundLoaderText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
    marginBottom: 14,
    textTransform: "lowercase",
  },
  loaderCircle: {
    alignItems: "center",
    borderRadius: 26,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  loaderRing: {
    borderColor: "rgba(255,255,255,0.35)",
    borderRadius: 26,
    borderTopColor: "#ffffff",
    borderWidth: 6,
    height: 52,
    width: 52,
  },
  creditPanel: {
    alignItems: "center",
    gap: 12,
    justifyContent: "center",
    minHeight: 120,
  },
  creditTitle: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "900",
  },
  creditButton: {
    alignItems: "center",
    backgroundColor: "#fff07a",
    borderRadius: 8,
    justifyContent: "center",
    minHeight: 54,
    minWidth: 150,
  },
  creditButtonText: {
    color: "#17201d",
    fontSize: 17,
    fontWeight: "900",
  },
  resultSplash: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 122,
  },
  resultAmount: {
    color: "#ffffff",
    fontSize: 42,
    fontWeight: "900",
    textShadowColor: "rgba(0,0,0,0.24)",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
  },
  resultWin: {
    color: "#fff07a",
  },
  resultLoss: {
    color: "#ffdddd",
  },
  resultLabel: {
    color: "#eafff3",
    fontSize: 17,
    fontWeight: "900",
    marginTop: 4,
    textTransform: "uppercase",
  },
  actionRow: {
    flexDirection: "row",
    gap: 14,
    justifyContent: "center",
  },
  dealingSpace: {
    minHeight: 80,
  },
  actionButton: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 58,
    minWidth: 130,
    borderRadius: 8,
  },
  hitButton: {
    backgroundColor: "#0fce68",
  },
  standButton: {
    backgroundColor: "#d63d3d",
  },
  actionText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "900",
  },
  disabled: {
    opacity: 0.45,
  },
  pressed: {
    opacity: 0.82,
  },
});
